import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Navigation
    nav: {
      companies: 'Companies',
      careers: 'Careers',
      about: 'About',
      contact: 'Contact',
    },
    // Home Page
    home: {
      label: 'Strategic Advisory',
      headline: 'Enterprise Risk.',
      headline2: 'Executive Careers.',
      subheadline: 'Governance that Accelerates. Careers that Scale. I build AI-driven, scalable risk frameworks for global enterprises, and mentor ambitious professionals to navigate rigorous Big Tech hiring processes.',
      cta1: 'Work with Me',
      cta2: 'Boost Your Career',
      trusted: 'Trusted Experience',
      location: 'Based in Barcelona',
      dualExpertise: 'Dual Expertise',
      dualTitle: 'Enterprise transformation meets career acceleration.',
      dualDesc: "Whether you're a global enterprise seeking robust governance frameworks, or an ambitious professional preparing for your defining career move — I provide strategic guidance that delivers measurable outcomes.",
      forEnterprises: 'For Enterprises',
      forProfessionals: 'For Professionals',
      managedPortfolios: 'Managed Portfolios',
      riskReduction: 'Risk Reduction',
      languages: 'Languages',
    },
    // Companies Page
    companies: {
      label: 'Corporate Advisory',
      headline: 'Resilient Systems',
      headline2: 'at Scale.',
      subheadline: 'Strategic governance frameworks that transform complexity into competitive advantage. From audit to implementation, I partner with global enterprises to build systems that scale.',
      service1Title: 'Governance Supportability & PMO',
      service1Desc: 'Audit IT pipelines and design governance frameworks that are robust, scalable, and built to last. Bridging the gap between technical innovation and business continuity — so your systems don\'t just work today, but remain governable tomorrow.',
      service1Item1: 'Enterprise-wide governance audits',
      service1Item2: 'Standardized framework design',
      service1Item3: 'Cross-functional alignment',
      service2Title: 'Quantitative Risk & AI Compliance',
      service2Desc: 'Tailored frameworks prioritizing quantitative models and advanced anomaly detection. Transition operations from reactive firefighting to proactive prevention.',
      service2Item1: 'FAIR methodology implementation',
      service2Item2: 'Cyber risk quantification',
      service2Item3: 'Predictive analytics integration',
      service3Title: 'Master Roadmaps & Resilience',
      service3Desc: 'Master Integration Roadmaps for global M&A consolidations. Automated Data Sanitization frameworks to ensure multi-jurisdictional compliance.',
      service3Item1: 'M&A integration strategy',
      service3Item2: 'Multi-jurisdictional compliance',
      service3Item3: 'Automated data sanitization',
      ctaLabel: 'Ready to Transform?',
      ctaTitle: "Let's architect your enterprise resilience.",
      ctaButton: 'Schedule Consultation',
    },
    // Careers Page
    careers: {
      label: 'Professional Mentorship',
      headline: 'Land Your',
      headline2: 'Defining Role.',
      subheadline: 'Strategic career guidance that transforms ambitious professionals into Big Tech leaders. I decode the hiring process so you can articulate your value with clarity and confidence.',
      service1Title: 'Big Tech Interview Mastery',
      service1Desc: '1:1 behavioral and technical coaching to decode the hiring process and master the STAR method. Understand what top companies truly look for and how to demonstrate it.',
      service1Item1: 'STAR method mastery',
      service1Item2: 'Mock interview sessions',
      service1Item3: 'Technical deep-dives',
      service2Title: 'Executive Presence & Storytelling',
      service2Desc: 'Learn to translate operational complexity into clear, compelling narratives that influence stakeholders. Build the presence that commands rooms and accelerates careers.',
      service2Item1: 'Narrative construction',
      service2Item2: 'Stakeholder influence',
      service2Item3: 'Leadership communication',
      service3Title: 'Career Elevation Strategy',
      service3Desc: 'Strategic mentorship to map your path to senior leadership and build a personalized roadmap. Navigate transitions, negotiate offers, and accelerate your trajectory.',
      service3Item1: 'Career trajectory mapping',
      service3Item2: 'Offer negotiation strategy',
      service3Item3: 'Leadership transition support',
      approachLabel: 'The Approach',
      approachQuote: '"I reverse-engineer the Big Tech hiring process to help ambitious professionals articulate their value and secure career-defining roles."',
      ctaLabel: 'Ready to Accelerate?',
      ctaTitle: "Let's map your path to leadership.",
      ctaButton: 'Book Your Session',
    },
    // About Page
    about: {
      label: 'About',
      headline: 'Global Expertise.',
      headline2: 'Human-Centric',
      headline3: 'Growth.',
      portfolios: 'Portfolios',
      languages: 'Languages',
      years: 'Years',
      yearsNumber: '7+',
      background: 'Background',
      bio1: 'With a career spanning $9B+ in managed portfolios — from risk management at Amazon and BNP Paribas to AI governance at Microsoft — I specialize in transforming complex regulatory requirements into streamlined, AI-driven operational frameworks. My approach bridges the gap between rigorous compliance and agile business growth, with a growing focus on how organizations govern systems they\'re still learning to understand.',
      bio2: 'As a trilingual leader (English, Portuguese, Spanish), I have successfully navigated the nuances of global markets, aligning cross-functional teams across continents to deliver robust risk management strategies.',
      bio3: 'Beyond enterprise consulting, I\'m deeply committed to mentoring the next generation of tech leaders. I reverse-engineer the Big Tech hiring process to help ambitious professionals articulate their value and secure career-defining roles.',
      location: 'Brazilian based in Barcelona, serving clients globally.',
      expertise: 'Expertise',
      expertiseGov: 'Enterprise Governance',
      expertiseGovItems: ['AI Governance & LLM Accountability', 'Risk Framework Design', 'Regulatory Compliance (AML, KYC, GDPR)', 'IT Governance & PMO', 'M&A Integration Strategy'],
      expertiseCareer: 'Career Development',
      expertiseCareerItems: ['Big Tech Interview Coaching', 'Executive Presence Training', 'Leadership Transition', 'Strategic Career Planning'],
      experience: 'Experience',
      experienceItems: [
        { company: 'Microsoft', role: 'Governance Supportability Portfolio Coordinator — AI governance, LLMs, and organizational accountability' },
        { company: 'Amazon', role: 'Senior Risk Manager — global risk frameworks protecting $9B+ in annual revenue' },
        { company: 'BNP Paribas', role: 'Credit Risk Analyst — regulatory compliance and portfolio risk management' }
      ],
      ctaLabel: "Let's Connect",
      ctaTitle: 'Ready to discuss your goals?',
      ctaButton: 'Get in Touch',
    },
    // Contact Page
    contact: {
      label: 'Contact',
      headline: "Let's Build",
      headline2: 'Your Strategy.',
      subheadline: "Schedule a complimentary, no-obligation 30-minute consultation. Let's discuss how we can accelerate your enterprise or career.",
      sendMessage: 'Send a Message',
      scheduleCall: 'Schedule a Call',
      messageSent: 'Message Sent',
      messageSentDesc: "Thank you for reaching out. I'll respond within 24-48 hours.",
      sendAnother: 'Send Another Message',
      namePlaceholder: 'Name',
      companyPlaceholder: 'Company',
      emailPlaceholder: 'Email',
      interestPlaceholder: 'I am interested in:',
      interestCorporate: 'Corporate Advisory',
      interestCareer: 'Career Mentorship',
      messagePlaceholder: 'Message',
      submitButton: 'Send Message',
      sending: 'Sending...',
      responseTime: 'Response Time',
      responseTimeDesc: 'I respond to all inquiries within 24-48 hours.',
      availability: 'Availability',
      availabilityDesc: 'Currently accepting new clients for Q2 2026.',
      languagesLabel: 'Languages',
      languagesDesc: 'English, Portuguese, Spanish',
      locationLabel: 'Location',
      locationDesc: 'Barcelona, Spain',
      error: 'Please fill in all fields.',
      errorGeneric: 'Something went wrong. Please try again.',
      // Booking card (replaces Calendly)
      bookingTitle: 'Book a 30-Minute Call',
      bookingDesc: "I'd love to connect. Send me a message through the form on the left, or reach out directly on LinkedIn — I typically respond within 24 hours and we can find a time that works.",
      bookingCta: 'Connect on LinkedIn',
    },
    // Footer
    footer: {
      tagline: 'Strategic advisory in governance, AI, and career mentorship for ambitious leaders.',
      navigation: 'Navigation',
      connect: 'Connect',
      email: 'Email',
      rights: 'Yasmin Lemke',
      tagline2: 'Barcelona, Spain',
    },
  },
  es: {
    // Navigation
    nav: {
      companies: 'Empresas',
      careers: 'Carreras',
      about: 'Sobre Mí',
      contact: 'Contacto',
    },
    // Home Page
    home: {
      label: 'Asesoría Estratégica',
      headline: 'Riesgo Empresarial.',
      headline2: 'Carreras Ejecutivas.',
      subheadline: 'Gobernanza que acelera. Carreras que escalan. Desarrollo marcos de riesgo impulsados por IA para empresas globales y preparo a profesionales ambiciosos para destacarse en los procesos de selección de Big Tech.',
      cta1: 'Trabaja Conmigo',
      cta2: 'Impulsa tu Carrera',
      trusted: 'Experiencia Verificada',
      location: 'Desde Barcelona',
      dualExpertise: 'Doble Expertise',
      dualTitle: 'Transformación empresarial y aceleración de carreras.',
      dualDesc: 'Ya sea una empresa global buscando marcos de gobernanza robustos, o un profesional ambicioso preparándose para su movimiento de carrera definitivo — ofrezco orientación estratégica que genera resultados medibles.',
      forEnterprises: 'Para Empresas',
      forProfessionals: 'Para Profesionales',
      managedPortfolios: 'Carteras Gestionadas',
      riskReduction: 'Reducción de Riesgo',
      languages: 'Idiomas',
    },
    // Companies Page
    companies: {
      label: 'Asesoría Corporativa',
      headline: 'Sistemas Resilientes',
      headline2: 'a Escala.',
      subheadline: 'Marcos de gobernanza estratégica que transforman la complejidad en ventaja competitiva. Desde auditoría hasta implementación, colaboro con empresas globales para construir sistemas que escalan.',
      service1Title: 'Gobernanza y PMO',
      service1Desc: 'Auditoría de pipelines de TI y diseño de marcos de gobernanza estandarizados para escala global. Conectando innovación técnica con continuidad del negocio.',
      service1Item1: 'Auditorías de gobernanza empresarial',
      service1Item2: 'Diseño de marcos estandarizados',
      service1Item3: 'Alineación interfuncional',
      service2Title: 'Riesgo Cuantitativo y Compliance con IA',
      service2Desc: 'Marcos personalizados priorizando modelos cuantitativos y detección avanzada de anomalías. Transición de operaciones reactivas a prevención proactiva.',
      service2Item1: 'Implementación metodología FAIR',
      service2Item2: 'Cuantificación de riesgo cibernético',
      service2Item3: 'Integración de analytics predictivo',
      service3Title: 'Roadmaps y Resiliencia',
      service3Desc: 'Roadmaps de Integración para consolidaciones M&A globales. Marcos de Sanitización de Datos automatizados para compliance multi-jurisdiccional.',
      service3Item1: 'Estrategia de integración M&A',
      service3Item2: 'Compliance multi-jurisdiccional',
      service3Item3: 'Sanitización de datos automatizada',
      ctaLabel: '¿Preparado para Transformar?',
      ctaTitle: 'Diseñemos la resiliencia de tu empresa.',
      ctaButton: 'Agendar Consulta',
    },
    // Careers Page
    careers: {
      label: 'Mentoría Profesional',
      headline: 'Conquista el Rol',
      headline2: 'que Cambiará tu Carrera.',
      subheadline: 'Orientación estratégica de carrera que transforma profesionales ambiciosos en líderes de Big Tech. Decodifico el proceso de selección para que puedas articular tu valor con claridad y confianza.',
      service1Title: 'Dominio de Entrevistas Big Tech',
      service1Desc: 'Coaching 1:1 conductual y técnico para decodificar el proceso de selección y dominar el método STAR. Entiende qué buscan realmente las grandes empresas.',
      service1Item1: 'Dominio del método STAR',
      service1Item2: 'Sesiones de entrevistas simuladas',
      service1Item3: 'Análisis técnico en profundidad',
      service2Title: 'Presencia Ejecutiva y Storytelling',
      service2Desc: 'Aprende a traducir complejidad operacional en narrativas claras y convincentes que influyan a stakeholders. Construye la presencia que domina reuniones.',
      service2Item1: 'Construcción de narrativas',
      service2Item2: 'Influencia de stakeholders',
      service2Item3: 'Comunicación de liderazgo',
      service3Title: 'Estrategia de Elevación de Carrera',
      service3Desc: 'Mentoría estratégica para trazar tu camino al liderazgo senior y construir un roadmap personalizado. Navega transiciones y negocia ofertas.',
      service3Item1: 'Mapeo de trayectoria de carrera',
      service3Item2: 'Estrategia de negociación de ofertas',
      service3Item3: 'Apoyo en transición de liderazgo',
      approachLabel: 'Mi Enfoque',
      approachQuote: '"Hago ingeniería inversa del proceso de selección de Big Tech para ayudar a profesionales ambiciosos a articular su valor y asegurar roles que definen carreras."',
      ctaLabel: '¿Preparado para Acelerar?',
      ctaTitle: 'Tracemos tu camino al liderazgo.',
      ctaButton: 'Reserva tu Sesión',
    },
    // About Page
    about: {
      label: 'Sobre Mí',
      headline: 'Expertise Global.',
      headline2: 'Crecimiento',
      headline3: 'Humano.',
      portfolios: 'Carteras',
      languages: 'Idiomas',
      years: 'Años',
      yearsNumber: '7+',
      background: 'Trayectoria',
      bio1: 'Con una carrera que abarca más de $9B en carteras gestionadas — desde la gestión de riesgos en Amazon y BNP Paribas hasta la gobernanza de IA en Microsoft — me especializo en transformar requisitos regulatorios complejos en marcos operacionales impulsados por IA. Mi enfoque conecta compliance riguroso con crecimiento ágil del negocio, con un enfoque creciente en cómo las organizaciones gobiernan sistemas que aún están aprendiendo a comprender.',
      bio2: 'Como líder trilingüe (inglés, portugués, español), he navegado con éxito los matices de mercados globales, alineando equipos interfuncionales en continentes para entregar estrategias robustas de gestión de riesgos.',
      bio3: 'Más allá de la consultoría empresarial, estoy profundamente comprometida con acompañar a la próxima generación de líderes tech. Hago ingeniería inversa del proceso de selección de Big Tech para ayudar a profesionales a asegurar roles que definen carreras.',
      location: 'Brasileña afincada en Barcelona, atendiendo clientes globalmente.',
      expertise: 'Expertise',
      expertiseGov: 'Gobernanza Empresarial',
      expertiseGovItems: ['Gobernanza de Inteligencia Artificial', 'Diseño de Marcos de Riesgo', 'Compliance Regulatorio (AML, KYC, GDPR)', 'Gobernanza TI y PMO', 'Estrategia de Integración M&A'],
      expertiseCareer: 'Desarrollo de Carrera',
      expertiseCareerItems: ['Coaching de Entrevistas Big Tech', 'Entrenamiento de Presencia Ejecutiva', 'Transición de Liderazgo', 'Planificación Estratégica de Carrera'],
      experience: 'Experiencia',
      experienceItems: [
        { company: 'Microsoft', role: 'Coordinadora de Portafolio de Gobernanza — gobernanza de IA, LLMs y responsabilidad organizacional' },
        { company: 'Amazon', role: 'Senior Risk Manager — marcos de riesgo global protegiendo más de US$9B en ingresos anuales' },
        { company: 'BNP Paribas', role: 'Analista de Riesgo de Crédito — compliance regulatorio y gestión de riesgo de cartera' }
      ],
      ctaLabel: 'Conectemos',
      ctaTitle: '¿Preparada para hablar de tus objetivos?',
      ctaButton: 'Contacta',
    },
    // Contact Page
    contact: {
      label: 'Contacto',
      headline: 'Construyamos',
      headline2: 'Tu Estrategia.',
      subheadline: 'Agenda una consulta gratuita de 30 minutos sin compromiso. Hablemos de cómo podemos acelerar tu empresa o carrera.',
      sendMessage: 'Enviar Mensaje',
      scheduleCall: 'Agendar Llamada',
      messageSent: 'Mensaje Enviado',
      messageSentDesc: 'Gracias por contactarme. Responderé en 24-48 horas.',
      sendAnother: 'Enviar Otro Mensaje',
      namePlaceholder: 'Nombre',
      companyPlaceholder: 'Empresa',
      emailPlaceholder: 'Email',
      interestPlaceholder: 'Me interesa:',
      interestCorporate: 'Asesoría Corporativa',
      interestCareer: 'Mentoría de Carrera',
      messagePlaceholder: 'Mensaje',
      submitButton: 'Enviar Mensaje',
      sending: 'Enviando...',
      responseTime: 'Tiempo de Respuesta',
      responseTimeDesc: 'Respondo todas las consultas en 24-48 horas.',
      availability: 'Disponibilidad',
      availabilityDesc: 'Actualmente aceptando nuevos clientes para Q2 2026.',
      languagesLabel: 'Idiomas',
      languagesDesc: 'Inglés, Portugués, Español',
      locationLabel: 'Ubicación',
      locationDesc: 'Barcelona, España',
      error: 'Por favor completa todos los campos.',
      errorGeneric: 'Algo ha ido mal. Por favor inténtalo de nuevo.',
      // Booking card (replaces Calendly)
      bookingTitle: 'Agenda una Llamada de 30 Minutos',
      bookingDesc: 'Me encantaría conectar. Envíame un mensaje a través del formulario de la izquierda, o escríbeme directamente por LinkedIn — suelo responder en 24 horas y encontramos un momento que funcione.',
      bookingCta: 'Conectar en LinkedIn',
    },
    // Footer
    footer: {
      tagline: 'Asesoría estratégica en gobernanza e IA, y mentoría de carrera para líderes ambiciosos.',
      navigation: 'Navegación',
      connect: 'Conectar',
      email: 'Email',
      rights: 'Yasmin Lemke',
      tagline2: 'Barcelona, España',
    },
  },
  pt: {
    // Navigation
    nav: {
      companies: 'Empresas',
      careers: 'Carreiras',
      about: 'Sobre',
      contact: 'Contato',
    },
    // Home Page
    home: {
      label: 'Assessoria Estratégica',
      headline: 'Risco Empresarial.',
      headline2: 'Carreiras Executivas.',
      subheadline: 'Governança que acelera. Carreiras que escalam. Desenvolvo frameworks de risco orientados por IA para empresas globais e preparo profissionais ambiciosos para dominar os processos seletivos de Big Tech.',
      cta1: 'Vamos Conversar',
      cta2: 'Acelere sua Carreira',
      trusted: 'Experiência Comprovada',
      location: 'De Barcelona para o mundo',
      dualExpertise: 'Dupla Expertise',
      dualTitle: 'Transformação empresarial encontra aceleração de carreiras.',
      dualDesc: 'Seja uma empresa global buscando frameworks de governança robustos, ou um profissional ambicioso se preparando para o próximo grande passo — entrego orientação estratégica com resultados mensuráveis.',
      forEnterprises: 'Para Empresas',
      forProfessionals: 'Para Profissionais',
      managedPortfolios: 'Portfólios Gerenciados',
      riskReduction: 'Redução de Risco',
      languages: 'Idiomas',
    },
    // Companies Page
    companies: {
      label: 'Assessoria Corporativa',
      headline: 'Sistemas Resilientes',
      headline2: 'em Escala.',
      subheadline: 'Frameworks de governança estratégica que transformam complexidade em vantagem competitiva. Da auditoria à implementação, trabalho com empresas globais para construir sistemas que escalam.',
      service1Title: 'Governança e PMO',
      service1Desc: 'Auditoria de pipelines de TI e design de frameworks de governança padronizados para escala global. Conectando inovação técnica com continuidade do negócio.',
      service1Item1: 'Auditorias de governança empresarial',
      service1Item2: 'Design de frameworks padronizados',
      service1Item3: 'Alinhamento entre áreas',
      service2Title: 'Risco Quantitativo e Compliance com IA',
      service2Desc: 'Frameworks customizados priorizando modelos quantitativos e detecção avançada de anomalias. Sair do modo apagar incêndio para prevenção proativa.',
      service2Item1: 'Implementação metodologia FAIR',
      service2Item2: 'Quantificação de risco cibernético',
      service2Item3: 'Integração de analytics preditivo',
      service3Title: 'Roadmaps e Resiliência',
      service3Desc: 'Roadmaps de Integração para consolidações M&A globais. Frameworks de Sanitização de Dados automatizados para compliance multi-jurisdicional.',
      service3Item1: 'Estratégia de integração M&A',
      service3Item2: 'Compliance multi-jurisdicional',
      service3Item3: 'Sanitização de dados automatizada',
      ctaLabel: 'Pronto pra Transformar?',
      ctaTitle: 'Vamos desenhar a resiliência da sua empresa.',
      ctaButton: 'Agendar Conversa',
    },
    // Careers Page
    careers: {
      label: 'Mentoria Profissional',
      headline: 'Conquiste seu',
      headline2: 'Próximo Nível.',
      subheadline: 'Orientação estratégica de carreira que transforma profissionais ambiciosos em líderes de Big Tech. Decodifico o processo seletivo para você articular seu valor com clareza e confiança.',
      service1Title: 'Domínio de Entrevistas Big Tech',
      service1Desc: 'Coaching 1:1 comportamental e técnico para decodificar o processo seletivo e dominar o método STAR. Entenda o que as grandes empresas realmente buscam.',
      service1Item1: 'Domínio do método STAR',
      service1Item2: 'Simulações de entrevista',
      service1Item3: 'Aprofundamentos técnicos',
      service2Title: 'Presença Executiva e Storytelling',
      service2Desc: 'Aprenda a traduzir complexidade operacional em narrativas claras e impactantes que influenciam stakeholders. Construa a presença que lidera reuniões.',
      service2Item1: 'Construção de narrativas',
      service2Item2: 'Influência de stakeholders',
      service2Item3: 'Comunicação de liderança',
      service3Title: 'Estratégia de Aceleração de Carreira',
      service3Desc: 'Mentoria estratégica para mapear seu caminho para liderança sênior e construir um roadmap personalizado. Navegue transições e negocie ofertas.',
      service3Item1: 'Mapeamento de trajetória',
      service3Item2: 'Estratégia de negociação',
      service3Item3: 'Suporte em transição de liderança',
      approachLabel: 'A Abordagem',
      approachQuote: '"Faço engenharia reversa do processo seletivo de Big Tech para ajudar profissionais ambiciosos a articular seu valor e conquistar posições que transformam carreiras."',
      ctaLabel: 'Pronto pra Acelerar?',
      ctaTitle: 'Vamos mapear seu caminho para a liderança.',
      ctaButton: 'Agende sua Sessão',
    },
    // About Page
    about: {
      label: 'Sobre',
      headline: 'Expertise Global.',
      headline2: 'Crescimento',
      headline3: 'Humano.',
      portfolios: 'Portfólios',
      languages: 'Idiomas',
      years: 'Anos',
      yearsNumber: '7+',
      background: 'Trajetória',
      bio1: 'Com uma carreira que soma mais de $9B em portfólios gerenciados — da gestão de risco na Amazon e BNP Paribas até a governança de IA na Microsoft — me especializo em transformar requisitos regulatórios complexos em sistemas operacionais orientados por IA. Minha abordagem conecta compliance rigoroso com crescimento ágil do negócio, com foco crescente em como organizações governam sistemas que ainda estão aprendendo a entender.',
      bio2: 'Como líder trilíngue (inglês, português, espanhol), naveguei com sucesso as nuances de mercados globais, alinhando equipes multifuncionais em diferentes continentes para entregar estratégias robustas de gestão de riscos.',
      bio3: 'Além da consultoria empresarial, sou profundamente comprometida em preparar a próxima geração de líderes tech. Faço engenharia reversa do processo seletivo de Big Tech para ajudar profissionais a conquistar posições que transformam carreiras.',
      location: 'Brasileira baseada em Barcelona, atendendo clientes globalmente.',
      expertise: 'Expertise',
      expertiseGov: 'Governança Empresarial',
      expertiseGovItems: ['Governança de Inteligência Artificial', 'Design de Frameworks de Risco', 'Compliance Regulatório (AML, KYC, GDPR)', 'Governança TI e PMO', 'Estratégia de Integração M&A'],
      expertiseCareer: 'Desenvolvimento de Carreira',
      expertiseCareerItems: ['Coaching de Entrevistas Big Tech', 'Treinamento de Presença Executiva', 'Transição de Liderança', 'Planejamento Estratégico de Carreira'],
      experience: 'Experiência',
      experienceItems: [
        { company: 'Microsoft', role: 'Coordenadora de Portfólio de Governança — governança de IA, LLMs e responsabilidade organizacional' },
        { company: 'Amazon', role: 'Senior Risk Manager — frameworks de risco global protegendo mais de US$9B em receita anual' },
        { company: 'BNP Paribas', role: 'Analista de Risco de Crédito — compliance regulatório e gestão de risco de portfólio' }
      ],
      ctaLabel: 'Vamos Conectar',
      ctaTitle: 'Pronta pra falar sobre seus objetivos?',
      ctaButton: 'Entre em Contato',
    },
    // Contact Page
    contact: {
      label: 'Contato',
      headline: 'Vamos Construir',
      headline2: 'Sua Estratégia.',
      subheadline: 'Agende uma conversa gratuita de 30 minutos, sem compromisso. Vamos discutir como acelerar sua empresa ou carreira.',
      sendMessage: 'Enviar Mensagem',
      scheduleCall: 'Agendar Ligação',
      messageSent: 'Mensagem Enviada',
      messageSentDesc: 'Valeu por entrar em contato! Respondo em 24-48 horas.',
      sendAnother: 'Enviar Outra Mensagem',
      namePlaceholder: 'Nome',
      companyPlaceholder: 'Empresa',
      emailPlaceholder: 'Email',
      interestPlaceholder: 'Tenho interesse em:',
      interestCorporate: 'Assessoria Corporativa',
      interestCareer: 'Mentoria de Carreira',
      messagePlaceholder: 'Mensagem',
      submitButton: 'Enviar Mensagem',
      sending: 'Enviando...',
      responseTime: 'Tempo de Resposta',
      responseTimeDesc: 'Respondo todas as mensagens em 24-48 horas.',
      availability: 'Disponibilidade',
      availabilityDesc: 'Aceitando novos clientes para Q2 2026.',
      languagesLabel: 'Idiomas',
      languagesDesc: 'Inglês, Português, Espanhol',
      locationLabel: 'Localização',
      locationDesc: 'Barcelona, Espanha',
      error: 'Por favor preencha todos os campos.',
      errorGeneric: 'Ops, algo deu errado. Tenta de novo?',
      // Booking card (replaces Calendly)
      bookingTitle: 'Agende uma Conversa de 30 Minutos',
      bookingDesc: 'Adoraria conectar. Envie uma mensagem pelo formulário ao lado, ou entre em contato diretamente pelo LinkedIn — costumo responder em até 24 horas e encontramos um horário juntos.',
      bookingCta: 'Conectar no LinkedIn',
    },
    // Footer
    footer: {
      tagline: 'Assessoria estratégica em governança, IA e mentoria de carreira para líderes ambiciosos.',
      navigation: 'Navegação',
      connect: 'Conectar',
      email: 'Email',
      rights: 'Yasmin Lemke',
      tagline2: 'Barcelona, Espanha',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language');
      if (saved && ['en', 'es', 'pt'].includes(saved)) return saved;
    }
    return 'en'; // Default to English
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
