import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    nav: {
      mentoring: 'Advisory',
      courses: 'Courses',
      about: 'About',
      contact: 'Contact',
    },
    home: {
      label: 'AI Courses — Coming Soon',
      headline: 'Learn AI.',
      headline2: 'Advance Your Career.',
      subheadline: 'Practical AI courses from someone who has navigated Microsoft, Amazon and BNP Paribas. Join the waitlist for early access and founding member pricing.',
      cta1: 'Join the Waitlist',
      cta2: 'Explore Advisory',
      trusted: 'Instructor Experience',
      location: 'Based in Barcelona',
      dualExpertise: 'The Approach',
      dualTitle: 'Deep regulatory expertise. Practical career strategy.',
      dualDesc: 'With 7+ years navigating governance, risk and compliance across banking, fintech and enterprise technology, I translate real-world industry experience into actionable strategies for professionals targeting AI GRC, cybersecurity and Big Tech roles.',
      forProfessionals: 'Start Your Journey',
      managedPortfolios: 'Years in GRC',
      languages: 'Languages',
      bigTech: 'Big Tech',
      aiCourses: 'AI Courses',
      coursesLabel: "What's Coming",
      coursesHeadline: '5 courses. One goal: your next level.',
      coursesDesc: 'Practical, focused, and built around real experience — not theory. Early access members get founding pricing.',
      coursesBadge: 'Coming Soon',
      coursesCta: 'Get Early Access',
      coursesNote: 'Limited spots · Founding pricing · No commitment',
    },
    mentoring: {
      label: 'Career Advisory',
      headline: 'Your Path into',
      headline2: 'AI, Big Tech & Cybersecurity.',
      subheadline: 'Strategic guidance for professionals pivoting into AI governance, risk management, cybersecurity and Big Tech roles. I bring real industry experience from banking compliance to enterprise technology governance.',
      service1Title: 'AI GRC Career Transition',
      service1Desc: 'Structured advisory to help you move from your current role into AI Governance, Risk & Compliance. We map your transferable skills and build your narrative around emerging AI regulatory frameworks.',
      service1Item1: 'Skills gap analysis & positioning',
      service1Item2: 'AI governance frameworks (EU AI Act, NIST AI RMF, ISO 42001)',
      service1Item3: 'Interview preparation for GRC roles',
      service2Title: 'Cybersecurity Career Pathways',
      service2Desc: 'Navigate the cybersecurity landscape with confidence. From understanding which certifications matter to how to position yourself for leadership roles in information security.',
      service2Item1: 'Career pathway mapping',
      service2Item2: 'Certification strategy (CISSP, CISM, CRISC)',
      service2Item3: 'Leadership positioning in security',
      service3Title: 'Executive Interview Coaching',
      service3Desc: 'Build the communication skills and strategic narrative to land senior roles. Learn to articulate your expertise in executive-level interviews and stakeholder conversations.',
      service3Item1: 'STAR method for compliance roles',
      service3Item2: 'Mock interviews for senior positions',
      service3Item3: 'Offer negotiation strategy',
      service4Title: 'Big Tech Career Entry',
      service4Desc: "Structured guidance for professionals targeting roles at Microsoft, Amazon, Google, Meta and other global tech companies. I've been on the inside — I know what it takes to get in and grow.",
      service4Item1: 'Big Tech CV and LinkedIn optimisation',
      service4Item2: 'Interview loops and assessment preparation',
      service4Item3: 'Compensation negotiation and offer evaluation',
      approachLabel: 'The Method',
      approachQuote: '"I help professionals use their existing expertise as a bridge into AI governance, cybersecurity and Big Tech — so you don\'t start from scratch, you accelerate."',
      ctaLabel: 'Ready to Transition?',
      ctaTitle: "Let's map your path to AI GRC or Big Tech.",
      ctaButton: 'Book a Consultation',
    },
    courses: {
      label: 'AI Courses',
      headline: 'Learn AI.',
      headline2: 'Work Smarter.',
      subheadline: 'Practical, jargon-free AI courses for professionals who want to use artificial intelligence to advance their careers — no technical background needed.',
      formatTitle: 'How It Works',
      formatVideo: 'Pre-recorded video lessons — learn at your own pace, anywhere',
      formatQa: 'Async Q&A — submit your questions and get direct answers from Yasmin',
      formatCert: 'Certificate of completion included with every course',
      level: 'Level',
      duration: 'Duration',
      beginner: 'Beginner',
      intermediate: 'Intermediate',
      advanced: 'Advanced',
      enroll: 'Join Waitlist',
      comingSoon: 'Coming Soon',
      videoLessons: 'Video lessons',
      qaAccess: 'Q&A with Yasmin',
      selfPaced: 'Self-paced',
      course1Title: 'Claude for You',
      course1Desc: 'Discover how to set up and use Claude AI to handle your emails, research, reports and daily tasks. No tech background needed — just results.',
      course1Level: 'Beginner',
      course1Duration: '3 hours',
      course2Title: 'Prompt Like a Pro',
      course2Desc: 'Master the art of talking to AI. Get dramatically better results from ChatGPT, Claude and other tools with proven prompt frameworks used by professionals.',
      course2Level: 'Beginner',
      course2Duration: '4 hours',
      course3Title: 'AI Job Search Accelerator',
      course3Desc: 'Use AI to write standout CVs, prepare for interviews, research companies and land your next role — including Big Tech companies.',
      course3Level: 'Beginner',
      course3Duration: '5 hours',
      course4Title: 'Break Into Big Tech',
      course4Desc: 'A structured roadmap for professionals targeting Microsoft, Amazon, Google, Meta and other global tech companies. From positioning to signed offer.',
      course4Level: 'Intermediate',
      course4Duration: '6 hours',
      course5Title: 'AI GRC Launchpad',
      course5Desc: 'Your complete career starter kit for AI Governance, Risk & Compliance. Understand the EU AI Act, NIST AI RMF, ISO 42001 and how to position yourself as a GRC professional.',
      course5Level: 'Intermediate',
      course5Duration: '8 hours',
      oneOnOneTitle: '1:1 Private Sessions',
      oneOnOneDesc: 'For professionals who want dedicated, personalised guidance. Work directly with Yasmin in private sessions tailored entirely to your goals, your background and your timeline.',
      oneOnOneItem1: 'Fully personalised career strategy',
      oneOnOneItem2: 'Direct feedback on your CV, LinkedIn and positioning',
      oneOnOneItem3: 'Priority access and ongoing support between sessions',
      oneOnOneButton: 'Apply for 1:1 Sessions',
      ctaTitle: 'Not sure where to start?',
      ctaDesc: "Book a free 30-minute call and I'll map the right learning path for your goals.",
      ctaButton: 'Book a Free Call',
    },
    about: {
      label: 'About',
      headline: 'Regulatory Depth.',
      headline2: 'Career',
      headline3: 'Clarity.',
      portfolios: 'Sectors',
      languages: 'Languages',
      years: 'Years',
      yearsNumber: '7+',
      background: 'Background',
      bio1: 'My career spans governance, risk and compliance across three sectors: banking credit risk at BNP Paribas, financial technology, and enterprise Big Tech. This cross-sector experience gives me a practical understanding of how compliance frameworks evolve — and how to position that expertise in today\'s AI-driven regulatory landscape.',
      bio2: 'As a trilingual professional (English, Portuguese, Spanish), I have worked with cross-functional teams across Europe and the Americas, navigating the nuances of international regulatory environments including the EU AI Act, GDPR and financial services compliance.',
      bio3: 'I am deeply committed to helping the next generation of AI GRC, cybersecurity and Big Tech professionals. My advisory work is grounded in real industry experience — built across banking, fintech and enterprise technology.',
      location: 'Brazilian based in Barcelona, serving clients globally.',
      expertise: 'Expertise',
      expertiseCareer: 'Advisory Areas',
      expertiseCareerItems: ['AI Governance & Compliance (EU AI Act, NIST AI RMF)', 'Cybersecurity Career Strategy', 'Big Tech Career Entry', 'Executive Interview Coaching', 'Career Transition Planning', 'Offer & Compensation Negotiation'],
      experience: 'Experience',
      experienceItems: [
        { company: 'Microsoft', role: 'Governance & AI — Enterprise technology governance in regulated environments' },
        { company: 'Amazon', role: 'Risk Management — Global risk frameworks and operational risk oversight' },
        { company: 'BNP Paribas', role: 'Credit Risk — Banking compliance, portfolio governance and regulatory reporting' }
      ],
      ctaLabel: "Let's Connect",
      ctaTitle: 'Ready to discuss your goals?',
      ctaButton: 'Get in Touch',
    },
    contact: {
      label: 'Contact',
      headline: "Let's Align",
      headline2: 'Your Future.',
      subheadline: "Schedule a complimentary, no-obligation 30-minute consultation. Let's discuss how we can accelerate your path into AI GRC, cybersecurity or Big Tech.",
      sendMessage: 'Send a Message',
      scheduleCall: 'Schedule a Call',
      messageSent: 'Message Sent',
      messageSentDesc: "Thank you for reaching out. I'll respond within 24-48 hours.",
      sendAnother: 'Send Another Message',
      namePlaceholder: 'Name',
      companyPlaceholder: 'Current Company (Optional)',
      emailPlaceholder: 'Email',
      interestPlaceholder: 'I am interested in:',
      interestOption1: 'AI GRC Career Transition',
      interestOption2: 'Cybersecurity Career Advisory',
      interestOption3: 'Executive Interview Coaching',
      interestOption4: 'Big Tech Career Entry',
      interestOption5: 'AI Courses',
      interestOption6: '1:1 Private Sessions',
      messagePlaceholder: 'Message',
      submitButton: 'Send Message',
      sending: 'Sending...',
      responseTime: 'Response Time',
      responseTimeDesc: 'I respond to all inquiries within 24-48 hours.',
      availability: 'Availability',
      availabilityDesc: 'Currently accepting new clients for Q2 2026.',
      languagesLabel: 'Languages',
      languagesDesc: 'English, Portuguese, Spanish',
      locationLabel: 'Location',
      locationDesc: 'Barcelona, Spain',
      error: 'Please fill in all fields.',
      errorGeneric: 'Something went wrong. Please try again.',
      bookingTitle: 'Book a 30-Minute Call',
      bookingDesc: "I'd love to connect. Send me a message through the form, or reach out directly on LinkedIn — I typically respond within 24 hours.",
      bookingCta: 'Connect on LinkedIn',
    },
    footer: {
      tagline: 'AI consulting and career advisory for professionals targeting AI governance, cybersecurity and Big Tech.',
      navigation: 'Navigation',
      connect: 'Connect',
      email: 'Email',
      rights: 'Yasmin Lemke',
      tagline2: 'Barcelona, Spain',
    },
  },
  es: {
    nav: {
      mentoring: 'Asesoría',
      courses: 'Cursos',
      about: 'Sobre Mí',
      contact: 'Contacto',
    },
    home: {
      label: 'Cursos de IA — Próximamente',
      headline: 'Aprende IA.',
      headline2: 'Avanza tu Carrera.',
      subheadline: 'Cursos prácticos de IA de alguien que ha navegado Microsoft, Amazon y BNP Paribas. Únete a la lista de espera para acceso anticipado y precio de fundador.',
      cta1: 'Unirse a la Lista de Espera',
      cta2: 'Ver Asesoría',
      trusted: 'Experiencia de la Instructora',
      location: 'Desde Barcelona',
      dualExpertise: 'El Enfoque',
      dualTitle: 'Experiencia regulatoria profunda. Estrategia de carrera práctica.',
      dualDesc: 'Con más de 7 años navegando gobernanza, riesgo y cumplimiento en banca, fintech y tecnología empresarial, traduzco experiencia real del sector en estrategias accionables para profesionales que apuntan a GRC de IA, ciberseguridad y Big Tech.',
      forProfessionals: 'Comienza tu Camino',
      managedPortfolios: 'Años en GRC',
      languages: 'Idiomas',
      bigTech: 'Big Tech',
      aiCourses: 'Cursos de IA',
      coursesLabel: 'Lo Que Viene',
      coursesHeadline: '5 cursos. Un objetivo: tu próximo nivel.',
      coursesDesc: 'Prácticos, enfocados y con experiencia real — no teoría. Los miembros fundadores obtienen precio exclusivo.',
      coursesBadge: 'Próximamente',
      coursesCta: 'Obtener Acceso Anticipado',
      coursesNote: 'Cupos limitados · Precio de fundador · Sin compromiso',
    },
    mentoring: {
      label: 'Asesoría de Carrera',
      headline: 'Tu Camino hacia',
      headline2: 'IA, Big Tech y Ciberseguridad.',
      subheadline: 'Orientación estratégica para profesionales que se reorientan hacia gobernanza de IA, gestión de riesgos, ciberseguridad y Big Tech. Aporto experiencia real del sector, desde el compliance bancario hasta la gobernanza tecnológica empresarial.',
      service1Title: 'Transición a GRC de IA',
      service1Desc: 'Asesoría estructurada para ayudarte a pasar de tu rol actual a la Gobernanza, Riesgo y Cumplimiento de IA. Identificamos tus habilidades transferibles y construimos tu narrativa en torno a los marcos regulatorios emergentes.',
      service1Item1: 'Análisis de brechas de habilidades y posicionamiento',
      service1Item2: 'Marcos de gobernanza de IA (EU AI Act, NIST AI RMF, ISO 42001)',
      service1Item3: 'Preparación de entrevistas para roles GRC',
      service2Title: 'Trayectorias en Ciberseguridad',
      service2Desc: 'Navega el panorama de la ciberseguridad con confianza. Desde comprender qué certificaciones importan hasta cómo posicionarte para roles de liderazgo en seguridad de la información.',
      service2Item1: 'Mapeo de trayectoria profesional',
      service2Item2: 'Estrategia de certificaciones (CISSP, CISM, CRISC)',
      service2Item3: 'Posicionamiento de liderazgo en seguridad',
      service3Title: 'Coaching de Entrevistas Ejecutivas',
      service3Desc: 'Desarrolla las habilidades comunicativas y la narrativa estratégica para conseguir roles senior. Aprende a articular tu experiencia en entrevistas de nivel ejecutivo y conversaciones con stakeholders.',
      service3Item1: 'Método STAR para roles de compliance',
      service3Item2: 'Entrevistas simuladas para posiciones senior',
      service3Item3: 'Estrategia de negociación de ofertas',
      service4Title: 'Entrada a Big Tech',
      service4Desc: 'Orientación estructurada para profesionales que apuntan a roles en Microsoft, Amazon, Google, Meta y otras grandes empresas tecnológicas. He estado adentro — sé lo que se necesita para entrar y crecer.',
      service4Item1: 'Optimización de CV y LinkedIn para Big Tech',
      service4Item2: 'Preparación de entrevistas y assessments',
      service4Item3: 'Negociación de compensación y evaluación de ofertas',
      approachLabel: 'El Método',
      approachQuote: '"Ayudo a los profesionales a utilizar su experiencia actual como puente hacia la gobernanza de IA, la ciberseguridad y el Big Tech — para que no empieces de cero, sino que aceleres."',
      ctaLabel: '¿Lista para la Transición?',
      ctaTitle: 'Tracemos tu camino hacia GRC de IA o Big Tech.',
      ctaButton: 'Reserva una Consulta',
    },
    courses: {
      label: 'Cursos de IA',
      headline: 'Aprende IA.',
      headline2: 'Trabaja Mejor.',
      subheadline: 'Cursos prácticos de IA sin jerga técnica para profesionales que quieren usar la inteligencia artificial para avanzar en su carrera — sin necesidad de conocimientos técnicos.',
      formatTitle: 'Cómo Funciona',
      formatVideo: 'Lecciones en vídeo pregrabadas — aprende a tu ritmo, donde quieras',
      formatQa: 'Q&A asíncrona — envía tus dudas y recibe respuestas directas de Yasmin',
      formatCert: 'Certificado de finalización incluido en cada curso',
      level: 'Nivel',
      duration: 'Duración',
      beginner: 'Principiante',
      intermediate: 'Intermedio',
      advanced: 'Avanzado',
      enroll: 'Apuntarse a Lista de Espera',
      comingSoon: 'Próximamente',
      videoLessons: 'Lecciones en vídeo',
      qaAccess: 'Q&A con Yasmin',
      selfPaced: 'A tu ritmo',
      course1Title: 'Claude para Ti',
      course1Desc: 'Descubre cómo configurar y usar Claude IA para gestionar emails, investigación, informes y tareas diarias. Sin conocimientos técnicos — solo resultados.',
      course1Level: 'Principiante',
      course1Duration: '3 horas',
      course2Title: 'Prompt como un Pro',
      course2Desc: 'Domina el arte de hablar con la IA. Obtén resultados mucho mejores de ChatGPT, Claude y otras herramientas con marcos de prompts probados por profesionales.',
      course2Level: 'Principiante',
      course2Duration: '4 horas',
      course3Title: 'Acelerador de Búsqueda de Empleo con IA',
      course3Desc: 'Usa la IA para escribir CVs destacados, preparar entrevistas, investigar empresas y conseguir tu próximo rol — incluyendo empresas de Big Tech.',
      course3Level: 'Principiante',
      course3Duration: '5 horas',
      course4Title: 'Entra al Big Tech',
      course4Desc: 'Un roadmap estructurado para profesionales que apuntan a Microsoft, Amazon, Google, Meta y otras grandes tecnológicas. Desde el posicionamiento hasta la oferta firmada.',
      course4Level: 'Intermedio',
      course4Duration: '6 horas',
      course5Title: 'Lanzadera GRC de IA',
      course5Desc: 'Tu kit completo de inicio de carrera en Gobernanza, Riesgo y Cumplimiento de IA. Comprende el EU AI Act, NIST AI RMF, ISO 42001 y cómo posicionarte.',
      course5Level: 'Intermedio',
      course5Duration: '8 horas',
      oneOnOneTitle: 'Sesiones Privadas 1:1',
      oneOnOneDesc: 'Para profesionales que quieren orientación dedicada y personalizada. Trabaja directamente con Yasmin en sesiones privadas adaptadas completamente a tus objetivos, tu experiencia y tu ritmo.',
      oneOnOneItem1: 'Estrategia de carrera totalmente personalizada',
      oneOnOneItem2: 'Feedback directo sobre tu CV, LinkedIn y posicionamiento',
      oneOnOneItem3: 'Acceso prioritario y soporte continuo entre sesiones',
      oneOnOneButton: 'Solicitar Sesiones 1:1',
      ctaTitle: '¿No sabes por dónde empezar?',
      ctaDesc: 'Reserva una llamada gratuita de 30 minutos y trazaré el camino de aprendizaje correcto para tus objetivos.',
      ctaButton: 'Reserva una Llamada Gratuita',
    },
    about: {
      label: 'Sobre Mí',
      headline: 'Profundidad Regulatoria.',
      headline2: 'Claridad de',
      headline3: 'Carrera.',
      portfolios: 'Sectores',
      languages: 'Idiomas',
      years: 'Años',
      yearsNumber: '7+',
      background: 'Trayectoria',
      bio1: 'Mi carrera abarca gobernanza, riesgo y cumplimiento en tres sectores: riesgo de crédito bancario en BNP Paribas, tecnología financiera y tecnología empresarial de gran escala. Esta experiencia transversal me da una comprensión práctica de cómo evolucionan los marcos de compliance — y cómo posicionar esa experiencia en el entorno regulatorio impulsado por la IA de hoy.',
      bio2: 'Como profesional trilingüe (inglés, portugués, español), he trabajado con equipos interfuncionales en Europa y América, navegando los matices de entornos regulatorios internacionales como el Reglamento Europeo de IA, el RGPD y el compliance de servicios financieros.',
      bio3: 'Estoy profundamente comprometida con ayudar a la próxima generación de profesionales de GRC de IA, ciberseguridad y Big Tech. Mi asesoría se basa en experiencia real del sector — construida en banca, fintech y tecnología empresarial.',
      location: 'Brasileña afincada en Barcelona, atendiendo clientes globalmente.',
      expertise: 'Expertise',
      expertiseCareer: 'Áreas de Asesoría',
      expertiseCareerItems: ['Gobernanza y Compliance de IA (EU AI Act, NIST AI RMF)', 'Estrategia de Carrera en Ciberseguridad', 'Entrada a Big Tech', 'Coaching de Entrevistas Ejecutivas', 'Planificación de Transición de Carrera', 'Negociación de Oferta y Compensación'],
      experience: 'Experiencia',
      experienceItems: [
        { company: 'Microsoft', role: 'Gobernanza e IA — Gobernanza tecnológica empresarial en entornos regulados' },
        { company: 'Amazon', role: 'Gestión de Riesgos — Marcos globales de riesgo y supervisión de riesgo operacional' },
        { company: 'BNP Paribas', role: 'Riesgo de Crédito — Compliance bancario, gobernanza de carteras e informes regulatorios' }
      ],
      ctaLabel: 'Conectemos',
      ctaTitle: '¿Preparada para hablar de tus objetivos?',
      ctaButton: 'Contacta',
    },
    contact: {
      label: 'Contacto',
      headline: 'Alineemos',
      headline2: 'Tu Futuro.',
      subheadline: 'Agenda una consulta gratuita de 30 minutos sin compromiso. Hablemos de cómo acelerar tu camino hacia GRC de IA, ciberseguridad o Big Tech.',
      sendMessage: 'Enviar Mensaje',
      scheduleCall: 'Agendar Llamada',
      messageSent: 'Mensaje Enviado',
      messageSentDesc: 'Gracias por contactarme. Responderé en 24-48 horas.',
      sendAnother: 'Enviar Otro Mensaje',
      namePlaceholder: 'Nombre',
      companyPlaceholder: 'Empresa Actual (Opcional)',
      emailPlaceholder: 'Email',
      interestPlaceholder: 'Me interesa:',
      interestOption1: 'Transición a GRC de IA',
      interestOption2: 'Asesoría de Carrera en Ciberseguridad',
      interestOption3: 'Coaching de Entrevistas Ejecutivas',
      interestOption4: 'Entrada a Big Tech',
      interestOption5: 'Cursos de IA',
      interestOption6: 'Sesiones Privadas 1:1',
      messagePlaceholder: 'Mensaje',
      submitButton: 'Enviar Mensaje',
      sending: 'Enviando...',
      responseTime: 'Tiempo de Respuesta',
      responseTimeDesc: 'Respondo todas las consultas en 24-48 horas.',
      availability: 'Disponibilidad',
      availabilityDesc: 'Actualmente aceptando nuevos clientes para Q2 2026.',
      languagesLabel: 'Idiomas',
      languagesDesc: 'Inglés, Portugués, Español',
      locationLabel: 'Ubicación',
      locationDesc: 'Barcelona, España',
      error: 'Por favor completa todos los campos.',
      errorGeneric: 'Algo ha ido mal. Por favor inténtalo de nuevo.',
      bookingTitle: 'Agenda una Llamada de 30 Minutos',
      bookingDesc: 'Me encantaría conectar. Envíame un mensaje a través del formulario, o escríbeme directamente por LinkedIn — suelo responder en 24 horas.',
      bookingCta: 'Conectar en LinkedIn',
    },
    footer: {
      tagline: 'Consultoría de IA y asesoría de carrera para profesionales que apuntan a gobernanza de IA, ciberseguridad y Big Tech.',
      navigation: 'Navegación',
      connect: 'Conectar',
      email: 'Email',
      rights: 'Yasmin Lemke',
      tagline2: 'Barcelona, España',
    },
  },
  pt: {
    nav: {
      mentoring: 'Assessoria',
      courses: 'Cursos',
      about: 'Sobre',
      contact: 'Contato',
    },
    home: {
      label: 'Cursos de IA — Em Breve',
      headline: 'Aprenda IA.',
      headline2: 'Avance sua Carreira.',
      subheadline: 'Cursos práticos de IA por quem navegou Microsoft, Amazon e BNP Paribas. Entre na lista para acesso antecipado e preço de fundador.',
      cta1: 'Entrar na Lista de Espera',
      cta2: 'Ver Assessoria',
      trusted: 'Experiência da Instrutora',
      location: 'De Barcelona para o mundo',
      dualExpertise: 'A Abordagem',
      dualTitle: 'Profundidade regulatória. Estratégia de carreira prática.',
      dualDesc: 'Com mais de 7 anos navegando governança, risco e compliance em bancos, fintechs e tecnologia empresarial, traduzo experiência real do setor em estratégias concretas para profissionais que almejam GRC de IA, cibersegurança e Big Tech.',
      forProfessionals: 'Comece sua Jornada',
      managedPortfolios: 'Anos em GRC',
      languages: 'Idiomas',
      bigTech: 'Big Tech',
      aiCourses: 'Cursos de IA',
      coursesLabel: 'O Que Vem Por Aí',
      coursesHeadline: '5 cursos. Um objetivo: seu próximo nível.',
      coursesDesc: 'Práticos, focados e com experiência real — não teoria. Membros fundadores ganham preço exclusivo.',
      coursesBadge: 'Em Breve',
      coursesCta: 'Garantir Acesso Antecipado',
      coursesNote: 'Vagas limitadas · Preço de fundador · Sem compromisso',
    },
    mentoring: {
      label: 'Assessoria de Carreira',
      headline: 'Seu Caminho para',
      headline2: 'IA, Big Tech e Cibersegurança.',
      subheadline: 'Orientação estratégica para profissionais que desejam migrar para governança de IA, gestão de riscos, oibersegurança e Big Tech. Trago experiência real do setor, do compliance bancário à governança de tecnologia empresarial.',
      service1Title: 'Transição para GRC de IA',
      service1Desc: 'Assessoria estruturada para te ajudar a migrar da sua função atual para Governança, Risco e Compliance de IA. Mapeamos suas habilidades transferíveis e construímos sua narrativa em torno dos frameworks regulatórios emergentes.',
      service1Item1: 'Análise de lacunas de habilidades e posicionamento',
      service1Item2: 'Frameworks de governança de IA (EU AI Act, NIST AI RMF, ISO 42001)',
      service1Item3: 'Preparação de entrevistas para funções GRC',
      service2Title: 'Trajetórias em Cibersegurança',
      service2Desc: 'Navegue pelo cenário da cibersegurança com confiança. Desde entender quais certificações importam até como se posicionar para cargos de liderança em segurança da informação.',
      service2Item1: 'Mapeamento de trajetória profissional',
      service2Item2: 'Estratégia de certificações (CISSP, CISM, CRISC)',
      service2Item3: 'Posicionamento de liderança em segurança',
      service3Title: 'Coaching de Entrevistas Executivas',
      service3Desc: 'Desenvolva as habilidades de comunicação e a narrativa estratégica para conquistar cargos seniores. Aprenda a articular sua experiência em entrevistas de nível executivo e conversas com stakeholders.',
      service3Item1: 'Método STAR para funções de compliance',
      service3Item2: 'Simulações de entrevista para posições seniores',
      service3Item3: 'Estratégia de negociação de oferta',
      service4Title: 'Entrada no Big Tech',
      service4Desc: 'Orientação estruturada para profissionais que almejam cargos na Microsoft, Amazon, Google, Meta e outras grandes empresas de tecnologia. Já estive lá por dentro — sei o que é preciso para entrar e crescer.',
      service4Item1: 'Otimização de CV e LinkedIn para Big Tech',
      service4Item2: 'Preparação para entrevistas e assessments',
      service4Item3: 'Negociação de remuneração e avaliação de oferta',
      approachLabel: 'O Método',
      approachQuote: '"Ajudo profissionais a usar sua experiência atual como ponte para a governança de IA, a cibersegurança e o Big Tech — para que você não comece do zero, mas acelere."',
      ctaLabel: 'Pronta para a Transição?',
      ctaTitle: 'Vamos mapear seu caminho para GRC de IA ou Big Tech.',
      ctaButton: 'Agende uma Consulta',
    },
    courses: {
      label: 'Cursos de IA',
      headline: 'Aprenda IA.',
      headline2: 'Trabalhe Melhor.',
      subheadline: 'Cursos práticos de IA sem jargão técnico para profissionais que querem usar a inteligência artificial para avançar na carreira — sem precisar de conhecimento técnico.',
      formatTitle: 'Como Funciona',
      formatVideo: 'Aulas em vídeo gravadas — aprenda no seu ritmo, onde quiser',
      formatQa: 'Q&A assíncrono — envie suas dúvidas e receba respostas diretas da Yasmin',
      formatCert: 'Certificado de conclusão incluído em cada curso',
      level: 'Nível',
      duration: 'Duração',
      beginner: 'Iniciante',
      intermediate: 'Intermediário',
      advanced: 'Avançado',
      enroll: 'Entrar na Lista de Espera',
      comingSoon: 'Em Breve',
      videoLessons: 'Aulas em vídeo',
      qaAccess: 'Q&A com a Yasmin',
      selfPaced: 'No seu ritmo',
      course1Title: 'Claude para Você',
      course1Desc: 'Descubra como configurar e usar o Claude IA para gerenciar emails, pesquisas, relatórios e tarefas diárias. Sem conhecimento técnico — só resultados.',
      course1Level: 'Iniciante',
      course1Duration: '3 horas',
      course2Title: 'Prompt como um Pro',
      course2Desc: 'Domine a arte de conversar com a IA. Obtenha resultados muito melhores do ChatGPT, Claude e outras ferramentas com frameworks de prompts usados por profissionais.',
      course2Level: 'Iniciante',
      course2Duration: '4 horas',
      course3Title: 'Acelerador de Busca de Emprego com IA',
      course3Desc: 'Use IA para criar CVs que se destacam, se preparar para entrevistas, pesquisar empresas e conquistar sua próxima vaga — inclusive em empresas de Big Tech.',
      course3Level: 'Iniciante',
      course3Duration: '5 horas',
      course4Title: 'Entre no Big Tech',
      course4Desc: 'Um roadmap estruturado para profissionais que almejam Microsoft, Amazon, Google, Meta e outras grandes tecnológicas. Do posicionamento à oferta assinada.',
      course4Level: 'Intermediário',
      course4Duration: '6 horas',
      course5Title: 'GRC de IA: Do Zero ao Emprego',
      course5Desc: 'Seu kit completo para iniciar uma carreira em Governança, Risco e Compliance de IA. Entenda o EU AI Act, NIST AI RMF, ISO 42001 e como se posicionar no mercado.',
      course5Level: 'Intermediário',
      course5Duration: '8 horas',
      oneOnOneTitle: 'Sessões Privadas 1:1',
      oneOnOneDesc: 'Para profissionais que querem orientação dedicada e personalizada. Trabalhe diretamente com a Yasmin em sessões privadas totalmente adaptadas aos seus objetivos, sua trajetória e seu ritmo.',
      oneOnOneItem1: 'Estratégia de carreira totalmente personalizada',
      oneOnOneItem2: 'Feedback direto no seu CV, LinkedIn e posicionamento',
      oneOnOneItem3: 'Acesso prioritário e suporte contínuo entre sessões',
      oneOnOneButton: 'Candidatar-se às Sessões 1:1',
      ctaTitle: 'Não sabe por onde começar?',
      ctaDesc: 'Agende uma conversa gratuita de 30 minutos e vou mapear o caminho de aprendizado certo para seus objetivos.',
      ctaButton: 'Agendar Conversa Gratuita',
    },
    about: {
      label: 'Sobre',
      headline: 'Profundidade Regulatória.',
      headline2: 'Clareza de',
      headline3: 'Carreira.',
      portfolios: 'Setores',
      languages: 'Idiomas',
      years: 'Anos',
      yearsNumber: '7+',
      background: 'Trajetória',
      bio1: 'Minha carreira abrange governança, risco e compliance em três setores: risco de crédito bancário no BNP Paribas, tecnologia financeira e tecnologia empresarial de grande escala. Essa experiência multissetorial me dá uma compreensão prática de como os frameworks de compliance evoluem — e como posicionar essa expertise no cenário regulatório impulsionado pela IA de hoje.',
      bio2: 'Como profissional trilíngue (inglês, português, espanhol), trabalhei com equipes multifuncionais na Europa e nas Américas, navegando as nuances de ambientes regulatórios internacionais, incluindo o Regulamento Europeu de IA, o RGPD e o compliance de serviços financeiros.',
      bio3: 'Sou profundamente comprometida em ajudar a próxima geração de profissionais de GRC de IA, cibersegurança e Big Tech. Minha assessoria é baseada em experiência real do setor — construída em bancos, fintechs e tecnologia empresarial.',
      location: 'Brasileira baseada em Barcelona, atendendo clientes globalmente.',
      expertise: 'Expertise',
      expertiseCareer: 'Áreas de Assessoria',
      expertiseCareerItems: ['Governança e Compliance de IA (EU AI Act, NIST AI RMF)', 'Estratégia de Carreira em Cibersegurança', 'Entrada no Big Tech', 'Coaching de Entrevistas Executivas', 'Planejamento de Transição de Carreira', 'Negociação de Oferta e Remuneração'],
      experience: 'Experiência',
      experienceItems: [
        { company: 'Microsoft', role: 'Governança e IA — Governança de tecnologia empresarial em ambientes regulados' },
        { company: 'Amazon', role: 'Gestão de Riscos — Frameworks globais de risco e supervisão de risco operacional' },
        { company: 'BNP Paribas', role: 'Risco de Crédito — Compliance bancário, governança de carteiras e relatórios regulatórios' }
      ],
      ctaLabel: 'Vamos Conectar',
      ctaTitle: 'Pronta pra falar sobre seus objetivos?',
      ctaButton: 'Entre em Contato',
    },
    contact: {
      label: 'Contato',
      headline: 'Vamos Alinhar',
      headline2: 'Seu Futuro.',
      subheadline: 'Agende uma conversa gratuita de 30 minutos, sem compromisso. Vamos discutir como acelerar seu caminho para GRC de IA, cibersegurança ou Big Tech.',
      sendMessage: 'Enviar Mensagem',
      scheduleCall: 'Agendar Ligação',
      messageSent: 'Mensagem Enviada',
      messageSentDesc: 'Valeu por entrar em contato! Respondo em 24-48 horas.',
      sendAnother: 'Enviar Outra Mensagem',
      namePlaceholder: 'Nome',
      companyPlaceholder: 'Empresa Atual (Opcional)',
      emailPlaceholder: 'Email',
      interestPlaceholder: 'Tenho interesse em:',
      interestOption1: 'Transição para GRC de IA',
      interestOption2: 'Assessoria de Carreira em Cibersegurança',
      interestOption3: 'Coaching de Entrevistas Executivas',
      interestOption4: 'Entrada no Big Tech',
      interestOption5: 'Cursos de IA',
      interestOption6: 'Sessões Privadas 1:1',
      messagePlaceholder: 'Mensagem',
      submitButton: 'Enviar Mensagem',
      sending: 'Enviando...',
      responseTime: 'Tempo de Resposta',
      responseTimeDesc: 'Respondo todas as mensagens em 24-48 horas.',
      availability: 'Disponibilidade',
      availabilityDesc: 'Aceitando novos clientes para Q2 2026.',
      languagesLabel: 'Idiomas',
      languagesDesc: 'Inglês, Português, Espanhol',
      locationLabel: 'Localização',
      locationDesc: 'Barcelona, Espanha',
      error: 'Por favor preencha todos os campos.',
      errorGeneric: 'Ops, algo deu errado. Tenta de novo?',
      bookingTitle: 'Agende uma Conversa de 30 Minutos',
      bookingDesc: 'Adoraria conectar. Envie uma mensagem pelo formulário, ou entre em contato pelo LinkedIn — costumo responder em até 24 horas.',
      bookingCta: 'Conectar no LinkedIn',
    },
    footer: {
      tagline: 'Consultoria de IA e assessoria de carreira para profissionais que almejam governança de IA, cibersegurança e Big Tech.',
      navigation: 'Navegação',
      connect: 'Conectar',
      email: 'Email',
      rights: 'Yasmin Lemke',
      tagline2: 'Barcelona, Espanha',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language');
      if (saved && ['en', 'es', 'pt'].includes(saved)) return saved;
    }
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
