import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {

const translations = {
  en: {
    nav: {
      mentoring: 'Advisory',
      about: 'About',
      contact: 'Contact',
    },
    home: {
      label: 'Executive Career Advisor',
      headline: 'AI Governance.',
      headline2: 'Cybersecurity Careers.',
      subheadline: 'Strategic career advisory for professionals looking to transition into or advance within AI Governance, Risk & Compliance and cybersecurity — with clarity, confidence and a clear roadmap.',
      cta1: 'Explore Services',
      trusted: 'Experience Across',
      location: 'Based in Barcelona',
      dualExpertise: 'The Approach',
      dualTitle: 'Deep regulatory expertise. Practical career strategy.',
      dualDesc: 'With 7+ years navigating governance, risk and compliance across banking, fintech and enterprise technology, I translate real-world industry experience into actionable career strategies for the AI GRC and cybersecurity landscape.',
      forProfessionals: 'Start Your Journey',
      managedPortfolios: 'Years in GRC',
      languages: 'Languages',
    },
    mentoring: {
      label: 'Career Advisory',
      headline: 'Your Path into',
      headline2: 'AI GRC & Cybersecurity.',
      subheadline: 'Strategic guidance for professionals pivoting into AI governance, risk management and cybersecurity roles. I bring real industry experience from banking compliance to enterprise technology governance.',
      service1Title: 'AI GRC Career Transition',
      service1Desc: 'Structured advisory to help you move from your current role into AI Governance, Risk & Compliance. We map your transferable skills and build your narrative around emerging AI regulatory frameworks.',
      service1Item1: 'Skills gap analysis & positioning',
      service1Item2: 'AI governance frameworks (EU AI Act, NIST AI RMF, ISO 42001)',
      service1Item3: 'Interview preparation for GRC roles',
      service2Title: 'Cybersecurity Career Pathways',
      service2Desc: 'Navigate the cybersecurity landscape with confidence. From understanding which certifications matter to how to position yourself for leadership roles in information security.',
      service2Item1: 'Career pathway mapping',
      service2Item2: 'Certification strategy (CISSP, CISM, CRISC)',
      service2Item3: 'Leadership positioning in security',
      service3Title: 'Executive Interview Coaching',
      service3Desc: 'Build the communication skills and strategic narrative to land senior roles. Learn to articulate your expertise in executive-level interviews and stakeholder conversations.',
      service3Item1: 'STAR method for compliance roles',
      service3Item2: 'Mock interviews for senior positions',
      service3Item3: 'Offer negotiation strategy',
      approachLabel: 'The Method',
      approachQuote: '"I help professionals use their existing expertise as a bridge into AI governance and cybersecurity — so you don\'t start from scratch, you accelerate."',
      ctaLabel: 'Ready to Transition?',
      ctaTitle: "Let's map your path to AI GRC.",
      ctaButton: 'Book a Consultation',
    },
    about: {
      label: 'About',
      headline: 'Regulatory Depth.',
      headline2: 'Career',
      headline3: 'Clarity.',
      portfolios: 'Sectors',
      languages: 'Languages',
      years: 'Years',
      yearsNumber: '7+',
      background: 'Background',
      bio1: 'My career spans governance, risk and compliance across three sectors: banking credit risk at BNP Paribas, financial technology, and enterprise Big Tech. This cross-sector experience gives me a practical understanding of how compliance frameworks evolve — and how to position that expertise in today\'s AI-driven regulatory landscape.',
      bio2: 'As a trilingual professional (English, Portuguese, Spanish), I have worked with cross-functional teams across Europe and the Americas, navigating the nuances of international regulatory environments including the EU AI Act, GDPR and financial services compliance.',
      bio3: 'I am deeply committed to helping the next generation of AI GRC and cybersecurity professionals. My advisory work is grounded in real industry experience — built across banking, fintech and enterprise technology.',
      location: 'Brazilian based in Barcelona, serving clients globally.',
      expertise: 'Expertise',
      expertiseCareer: 'Advisory Areas',
      expertiseCareerItems: ['AI Governance & Compliance (EU AI Act, NIST AI RMF)', 'Cybersecurity Career Strategy', 'Executive Interview Coaching', 'Career Transition Planning', 'Offer & Compensation Negotiation'],
      experience: 'Experience',
      experienceItems: [
        { company: 'Microsoft', role: 'Governance & AI — Enterprise technology governance in regulated environments' },
        { company: 'Amazon', role: 'Risk Management — Global risk frameworks and operational risk oversight' },
        { company: 'BNP Paribas', role: 'Credit Risk — Banking compliance, portfolio governance and regulatory reporting' }
      ],
      ctaLabel: "Let's Connect",
      ctaTitle: 'Ready to discuss your goals?',
      ctaButton: 'Get in Touch',
    },
    contact: {
      label: 'Contact',
      headline: "Let's Align",
      headline2: 'Your Future.',
      subheadline: "Schedule a complimentary, no-obligation 30-minute consultation. Let's discuss how we can accelerate your path into AI GRC or cybersecurity.",
      sendMessage: 'Send a Message',
      scheduleCall: 'Schedule a Call',
      messageSent: 'Message Sent',
      messageSentDesc: "Thank you for reaching out. I'll respond within 24-48 hours.",
      sendAnother: 'Send Another Message',
      namePlaceholder: 'Name',
      companyPlaceholder: 'Current Company (Optional)',
      emailPlaceholder: 'Email',
      interestPlaceholder: 'I am interested in:',
      interestOption1: 'AI GRC Career Transition',
      interestOption2: 'Cybersecurity Career Advisory',
      interestOption3: 'Executive Interview Coaching',
      messagePlaceholder: 'Message',
      submitButton: 'Send Message',
      sending: 'Sending...',
      responseTime: 'Response Time',
      responseTimeDesc: 'I respond to all inquiries within 24-48 hours.',
      availability: 'Availability',
      availabilityDesc: 'Currently accepting new clients for Q2 2026.',
      languagesLabel: 'Languages',
      languagesDesc: 'English, Portuguese, Spanish',
      locationLabel: 'Location',
      locationDesc: 'Barcelona, Spain',
      error: 'Please fill in all fields.',
      errorGeneric: 'Something went wrong. Please try again.',
      bookingTitle: 'Book a 30-Minute Call',
      bookingDesc: "I'd love to connect. Send me a message through the form, or reach out directly on LinkedIn — I typically respond within 24 hours.",
      bookingCta: 'Connect on LinkedIn',
    },
    footer: {
      tagline: 'Executive career advisory for professionals navigating AI governance, risk & compliance and cybersecurity.',
      navigation: 'Navigation',
      connect: 'Connect',
      email: 'Email',
      rights: 'Yasmin Lemke',
      tagline2: 'Barcelona, Spain',
    },
  },
  es: {
    nav: {
      mentoring: 'Asesoría',
      about: 'Sobre Mí',
      contact: 'Contacto',
    },
    home: {
      label: 'Asesora de Carrera Ejecutiva',
      headline: 'Gobernanza de IA.',
      headline2: 'Carreras en Ciberseguridad.',
      subheadline: 'Asesoría estratégica de carrera para profesionales que desean incorporarse o avanzar en Gobernanza de IA, Riesgo & Cumplimiento y ciberseguridad — con claridad, confianza y un roadmap definido.',
      cta1: 'Explorar Servicios',
      trusted: 'Experiencia En',
      location: 'Desde Barcelona',
      dualExpertise: 'El Enfoque',
      dualTitle: 'Experiencia regulatoria profunda. Estrategia de carrera práctica.',
      dualDesc: 'Con más de 7 años navegando gobernanza, riesgo y cumplimiento en banca, fintech y tecnología empresarial, traduzco experiencia real del sector en estrategias de carrera accionables para el entorno de GRC de IA y ciberseguridad.',
      forProfessionals: 'Comienza tu Camino',
      managedPortfolios: 'Años en GRC',
      languages: 'Idiomas',
    },
    mentoring: {
      label: 'Asesoría de Carrera',
      headline: 'Tu Camino hacia',
      headline2: 'GRC de IA y Ciberseguridad.',
      subheadline: 'Orientación estratégica para profesionales que se reorientan hacia gobernanza de IA, gestión de riesgos y roles de ciberseguridad. Aporto experiencia real del sector, desde el compliance bancario hasta la gobernanza tecnológica empresarial.',
      service1Title: 'Transición a GRC de IA',
      service1Desc: 'Asesoría estructurada para ayudarte a pasar de tu rol actual a la Gobernanza, Riesgo y Cumplimiento de IA. Identificamos tus habilidades transferibles y construimos tu narrativa en torno a los marcos regulatorios emergentes.',
      service1Item1: 'Análisis de brechas de habilidades y posicionamiento',
      service1Item2: 'Marcos de gobernanza de IA (EU AI Act, NIST AI RMF, ISO 42001)',
      service1Item3: 'Preparación de entrevistas para roles GRC',
      service2Title: 'Trayectorias en Ciberseguridad',
      service2Desc: 'Navega el panorama de la ciberseguridad con confianza. Desde comprender qué certificaciones importan hasta cómo posicionarte para roles de liderazgo en seguridad de la información.',
      service2Item1: 'Mapeo de trayectoria profesional',
      service2Item2: 'Estrategia de certificaciones (CISSP, CISM, CRISC)',
      service2Item3: 'Posicionamiento de liderazgo en seguridad',
      service3Title: 'Coaching de Entrevistas Ejecutivas',
      service3Desc: 'Desarrolla las habilidades comunicativas y la narrativa estratégica para conseguir roles senior. Aprende a articular tu experiencia en entrevistas de nivel ejecutivo y conversaciones con stakeholders.',
      service3Item1: 'Método STAR para roles de compliance',
      service3Item2: 'Entrevistas simuladas para posiciones senior',
      service3Item3: 'Estrategia de negociación de ofertas',
      approachLabel: 'El Método',
      approachQuote: '"Ayudo a los profesionales a utilizar su experiencia actual como puente hacia la gobernanza de IA y la ciberseguridad — para que no empieces de cero, sino que aceleres."',
      ctaLabel: '¿Lista para la Transición?',
      ctaTitle: 'Tracemos tu camino hacia GRC de IA.',
      ctaButton: 'Reserva una Consulta',
    },
    about: {
      label: 'Sobre Mí',
      headline: 'Profundidad Regulatoria.',
      headline2: 'Claridad de',
      headline3: 'Carrera.',
      portfolios: 'Sectores',
      languages: 'Idiomas',
      years: 'Años',
      yearsNumber: '7+',
      background: 'Trayectoria',
      bio1: 'Mi carrera abarca gobernanza, riesgo y cumplimiento en tres sectores: riesgo de crédito bancario en BNP Paribas, tecnología financiera y tecnología empresarial de gran escala. Esta experiencia transversal me da una comprensión práctica de cómo evolucionan los marcos de compliance — y cómo posicionar esa experiencia en el entorno regulatorio impulsado por la IA de hoy.',
      bio2: 'Como profesional trilingüe (inglés, portugués, español), he trabajado con equipos interfuncionales en Europa y América, navegando los matices de entornos regulatorios internacionales como el Reglamento Europeo de IA, el RGPD y el compliance de servicios financieros.',
      bio3: 'Estoy profundamente comprometida con ayudar a la próxima generación de profesionales de GRC de IA y ciberseguridad. Mi asesoría se basa en experiencia real del sector — construida en banca, fintech y tecnología empresarial.',
      location: 'Brasileña afincada en Barcelona, atendiendo clientes globalmente.',
      expertise: 'Expertise',
      expertiseCareer: 'Áreas de Asesoría',
      expertiseCareerItems: ['Gobernanza y Compliance de IA (EU AI Act, NIST AI RMF)', 'Estrategia de Carrera en Ciberseguridad', 'Coaching de Entrevistas Ejecutivas', 'Planificación de Transición de Carrera', 'Negociación de Oferta y Compensación'],
      experience: 'Experiencia',
      experienceItems: [
        { company: 'Microsoft', role: 'Gobernanza e IA — Gobernanza tecnológica empresarial en entornos regulados' },
        { company: 'Amazon', role: 'Gestión de Riesgos — Marcos globales de riesgo y supervisión de riesgo operacional' },
        { company: 'BNP Paribas', role: 'Riesgo de Crédito — Compliance bancario, gobernanza de carteras e informes regulatorios' }
      ],
      ctaLabel: 'Conectemos',
      ctaTitle: '¿Preparada para hablar de tus objetivos?',
      ctaButton: 'Contacta',
    },
    contact: {
      label: 'Contacto',
      headline: 'Alineemos',
      headline2: 'Tu Futuro.',
      subheadline: 'Agenda una consulta gratuita de 30 minutos sin compromiso. Hablemos de cómo acelerar tu camino hacia GRC de IA o ciberseguridad.',
      sendMessage: 'Enviar Mensaje',
      scheduleCall: 'Agendar Llamada',
      messageSent: 'Mensaje Enviado',
      messageSentDesc: 'Gracias por contactarme. Responderé en 24-48 horas.',
      sendAnother: 'Enviar Otro Mensaje',
      namePlaceholder: 'Nombre',
      companyPlaceholder: 'Empresa Actual (Opcional)',
      emailPlaceholder: 'Email',
      interestPlaceholder: 'Me interesa:',
      interestOption1: 'Transición a GRC de IA',
      interestOption2: 'Asesoría de Carrera en Ciberseguridad',
      interestOption3: 'Coaching de Entrevistas Ejecutivas',
      messagePlaceholder: 'Mensaje',
      submitButton: 'Enviar Mensaje',
      sending: 'Enviando...',
      responseTime: 'Tiempo de Respuesta',
      responseTimeDesc: 'Respondo todas las consultas en 24-48 horas.',
      availability: 'Disponibilidad',
      availabilityDesc: 'Actualmente aceptando nuevos clientes para Q2 2026.',
      languagesLabel: 'Idiomas',
      languagesDesc: 'Inglés, Portugués, Español',
      locationLabel: 'Ubicación',
      locationDesc: 'Barcelona, España',
      error: 'Por favor completa todos los campos.',
      errorGeneric: 'Algo ha ido mal. Por favor inténtalo de nuevo.',
      bookingTitle: 'Agenda una Llamada de 30 Minutos',
      bookingDesc: 'Me encantaría conectar. Envíame un mensaje a través del formulario, o escríbeme directamente por LinkedIn — suelo responder en 24 horas.',
      bookingCta: 'Conectar en LinkedIn',
    },
    footer: {
      tagline: 'Asesoría de carrera ejecutiva para profesionales que navegan la gobernanza de IA, riesgo & cumplimiento y ciberseguridad.',
      navigation: 'Navegación',
      connect: 'Conectar',
      email: 'Email',
      rights: 'Yasmin Lemke',
      tagline2: 'Barcelona, España',
    },
  },
  pt: {
    nav: {
      mentoring: 'Assessoria',
      about: 'Sobre',
      contact: 'Contato',
    },
    home: {
      label: 'Assessora de Carreira Executiva',
      headline: 'Governança de IA.',
      headline2: 'Carreiras em Cibersegurança.',
      subheadline: 'Assessoria estratégica de carreira para profissionais que desejam ingressar ou avançar em Governança de IA, Risco & Compliance e cibersegurança — com clareza, confiança e um roadmap definido.',
      cta1: 'Explorar Serviços',
      trusted: 'Experiência Em',
      location: 'De Barcelona para o mundo',
      dualExpertise: 'A Abordagem',
      dualTitle: 'Profundidade regulatória. Estratégia de carreira prática.',
      dualDesc: 'Com mais de 7 anos navegando governança, risco e compliance em bancos, fintechs e tecnologia empresarial, traduzo experiência real do setor em estratégias de carreira concretas para o cenário de GRC de IA e cibersegurança.',
      forProfessionals: 'Comece sua Jornada',
      managedPortfolios: 'Anos em GRC',
      languages: 'Idiomas',
    },
    mentoring: {
      label: 'Assessoria de Carreira',
      headline: 'Seu Caminho para',
      headline2: 'GRC de IA e Cibersegurança.',
      subheadline: 'Orientação estratégica para profissionais que desejam migrar para governança de IA, gestão de riscos e funções de cibersegurança. Trago experiência real do setor, do compliance bancário à governança de tecnologia empresarial.',
      service1Title: 'Transição para GRC de IA',
      service1Desc: 'Assessoria estruturada para te ajudar a migrar da sua função atual para Governança, Risco e Compliance de IA. Mapeamos suas habilidades transferíveis e construímos sua narrativa em torno dos frameworks regulatórios emergentes.',
      service1Item1: 'Análise de lacunas de habilidades e posicionamento',
      service1Item2: 'Frameworks de governança de IA (EU AI Act, NIST AI RMF, ISO 42001)',
      service1Item3: 'Preparação de entrevistas para funções GRC',
      service2Title: 'Trajetórias em Cibersegurança',
      service2Desc: 'Navegue pelo cenário da cibersegurança com confiança. Desde entender quais certificações importam até como se posicionar para cargos de liderança em segurança da informação.',
      service2Item1: 'Mapeamento de trajetória profissional',
      service2Item2: 'Estratégia de certificações (CISSP, CISM, CRISC)',
      service2Item3: 'Posicionamento de liderança em segurança',
      service3Title: 'Coaching de Entrevistas Executivas',
      service3Desc: 'Desenvolva as habilidades de comunicação e a narrativa estratégica para conquistar cargos seniores. Aprenda a articular sua experiência em entrevistas de nível executivo e conversas com stakeholders.',
      service3Item1: 'Método STAR para funções de compliance',
      service3Item2: 'Simulações de entrevista para posições seniores',
      service3Item3: 'Estratégia de negociação de oferta',
      approachLabel: 'O Método',
      approachQuote: '"Ajudo profissionais a usar sua experiência atual como ponte para a governança de IA e a cibersegurança — para que você não comece do zero, mas acelere."',
      ctaLabel: 'Pronta para a Transição?',
      ctaTitle: 'Vamos mapear seu caminho para GRC de IA.',
      ctaButton: 'Agende uma Consulta',
    },
    about: {
      label: 'Sobre',
      headline: 'Profundidade Regulatória.',
      headline2: 'Clareza de',
      headline3: 'Carreira.',
      portfolios: 'Setores',
      languages: 'Idiomas',
      years: 'Anos',
      yearsNumber: '7+',
      background: 'Trajetória',
      bio1: 'Minha carreira abrange governança, risco e compliance em três setores: risco de crédito bancário no BNP Paribas, tecnologia financeira e tecnologia empresarial de grande escala. Essa experiência multissetorial me dá uma compreensão prática de como os frameworks de compliance evoluem — e como posicionar essa expertise no cenário regulatório impulsionado pela IA de hoje.',
      bio2: 'Como profissional trilíngue (inglês, português, espanhol), trabalhei com equipes multifuncionais na Europa e nas Américas, navegando as nuances de ambientes regulatórios internacionais, incluindo o Regulamento Europeu de IA, o RGPD e o compliance de serviços financeiros.',
      bio3: 'Sou profundamente comprometida em ajudar a próxima geração de profissionais de GRC de IA e cibersegurança. Minha assessoria é baseada em experiência real do setor — construída em bancos, fintechs e tecnologia empresarial.',
      location: 'Brasileira baseada em Barcelona, atendendo clientes globalmente.',
      expertise: 'Expertise',
      expertiseCareer: 'Áreas de Assessoria',
      expertiseCareerItems: ['Governança e Compliance de IA (EU AI Act, NIST AI RMF)', 'Estratégia de Carreira em Cibersegurança', 'Coaching de Entrevistas Executivas', 'Planejamento de Transição de Carreira', 'Negociação de Oferta e Remuneração'],
      experience: 'Experiência',
      experienceItems: [
        { company: 'Microsoft', role: 'Governança e IA — Governança de tecnologia empresarial em ambientes regulados' },
        { company: 'Amazon', role: 'Gestão de Riscos — Frameworks globais de risco e supervisão de risco operacional' },
        { company: 'BNP Paribas', role: 'Risco de Crédito — Compliance bancário, governança de carteiras e relatórios regulatórios' }
      ],
      ctaLabel: 'Vamos Conectar',
      ctaTitle: 'Pronta pra falar sobre seus objetivos?',
      ctaButton: 'Entre em Contato',
    },
    contact: {
      label: 'Contato',
      headline: 'Vamos Alinhar',
      headline2: 'Seu Futuro.',
      subheadline: 'Agende uma conversa gratuita de 30 minutos, sem compromisso. Vamos discutir como acelerar seu caminho para GRC de IA ou cibersegurança.',
      sendMessage: 'Enviar Mensagem',
      scheduleCall: 'Agendar Ligação',
      messageSent: 'Mensagem Enviada',
      messageSentDesc: 'Valeu por entrar em contato! Respondo em 24-48 horas.',
      sendAnother: 'Enviar Outra Mensagem',
      namePlaceholder: 'Nome',
      companyPlaceholder: 'Empresa Atual (Opcional)',
      emailPlaceholder: 'Email',
      interestPlaceholder: 'Tenho interesse em:',
      interestOption1: 'Transição para GRC de IA',
      interestOption2: 'Assessoria de Carreira em Cibersegurança',
      interestOption3: 'Coaching de Entrevistas Executivas',
      messagePlaceholder: 'Mensagem',
      submitButton: 'Enviar Mensagem',
      sending: 'Enviando...',
      responseTime: 'Tempo de Resposta',
      responseTimeDesc: 'Respondo todas as mensagens em 24-48 horas.',
      availability: 'Disponibilidade',
      availabilityDesc: 'Aceitando novos clientes para Q2 2026.',
      languagesLabel: 'Idiomas',
      languagesDesc: 'Inglês, Português, Espanhol',
      locationLabel: 'Localização',
      locationDesc: 'Barcelona, Espanha',
      error: 'Por favor preencha todos os campos.',
      errorGeneric: 'Ops, algo deu errado. Tenta de novo?',
      bookingTitle: 'Agende uma Conversa de 30 Minutos',
      bookingDesc: 'Adoraria conectar. Envie uma mensagem pelo formulário, ou entre em contato pelo LinkedIn — costumo responder em até 24 horas.',
      bookingCta: 'Conectar no LinkedIn',
    },
    footer: {
      tagline: 'Assessoria de carreira executiva para profissionais que navegam a governança de IA, risco & compliance e cibersegurança.',
      navigation: 'Navegação',
      connect: 'Conectar',
      email: 'Email',
      rights: 'Yasmin Lemke',
      tagline2: 'Barcelona, Espanha',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language');
      if (saved && ['en', 'es', 'pt'].includes(saved)) return saved;
    }
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
